# Сколько попыток обновления камеры совершить перед тем, как признать её нерабочей.
consequentRetries: 2

# Куда сохранять изображения с камер.
imagesPath: ./snapshots

# Размер изображений по горизонтали в пикселях.
imageSize: 320

# Порт для HTTP и WebSocket-сервера.
port: 8000

# Сколько видео обновлять одновременно.
# Слишком большие значения (4-8 и более) могут приводить к битым изображениям из-за
# ограничений канала.
parallelReloads: 1

# Тип видеопотока, получаемого от ipeye. Возможные значения: rtsp, rtmp и hls.
streamType: rtsp

# Тайм-аут в миллисекундах. В случае, если не удаётся получить изображение дольше, чем
# указано, то попытка обновления считается проваленной.
timeout: 30000

# Список камер.
#   name: произвольная строка
#   uuid: UUID камеры в системе ipeye - можно получить его из кода для вставки <iframe>
cameras: []

# Файл, в котором хранятся состояния камер
cameraStateFile: cameras.json
