backends:
  ipeye:
    # Тип видеопотока, получаемого от ipeye. Возможные значения: rtsp, rtmp и hls.
    streamType: rtsp

# Список камер.
#   name: произвольная строка
#   id: идентификатор камеры на бэкенде
#   backend: сервис (бэкенд), который использовать для данной камеры
cameras:
  - name: ipeye test
    id: d4ee855e40874ef7b7149357a42f18f0 # d4c0b85e21f347f59ca86b59684a498c
    backend: ipeye
  - name: rtsp.me test
    id: 43ydGsfs
    backend: rtsp.me

# Файл, в котором хранятся состояния камер
cameraStateFile: cameras.json

defaultBackend: ipeye

http:
  # Порт для HTTP и WebSocket-сервера.
  port: 8000

reloader:
  # Куда сохранять изображения с камер.
  imagesPath: ./snapshots

  # Размер изображений по горизонтали в пикселях.
  imageSize: 320

  # Тайм-аут в миллисекундах. В случае, если не удаётся получить изображение дольше, чем
  # указано, то попытка обновления считается проваленной.
  timeout: 30000

scheduler:
  # Сколько попыток обновления камеры совершить перед тем, как признать её нерабочей.
  consequentRetries: 2

  # Сколько видео обновлять одновременно.
  # Слишком большие значения (4-8 и более) могут приводить к битым изображениям из-за
  # ограничений канала.
  parallelReloads: 1
